import type { Event } from '@/lib/types/database'

// Fallback treści strony /letni/ (Air Camp — obóz letni) na czas, gdy Supabase
// nie jest podłączony. Treść zaimportowana z projektu Claude Design
// ("Air Squad - Letni (Obóz).dc.html", projekt 23a11689-…) — 11. edycja obozu,
// ośrodek ZOOM Przygoda w Janowie Lubelskim, 25.07–02.08.2026. Renderowana przez
// dedykowany CampView (components/seo/camp-view.tsx), nie generyczny EventView.
// Filmy i część galerii linkują bezpośrednio do plików na airsquad.pl (WordPress,
// wciąż live) — przenieść do Supabase Storage przed wygaszeniem WordPressa.
// Po podłączeniu i zaseedowaniu bazy wiersz z DB ma priorytet. Patrz [[supabase-before-launch]].
export const LETNI_EVENT: Event = {
  id: 'fallback-letni',
  slug: 'letni',
  title: 'Air Camp 2026',
  meta_title:
    'Air Camp 2026 — letni obóz sportowy dla dzieci i młodzieży | Air Squad',
  meta_description:
    'Air Camp 2026: akrobatyka, tricking, kajaki, longboardy, paintball. 25 lipca – 2 sierpnia 2026, Janów Lubelski. Małe grupy, dwóch trenerów. Zarezerwuj turnus!',
  event_type: 'oboz',
  event_date: '2026-07-25',
  event_time: null,
  location: 'Janów Lubelski, Ośrodek ZOOM Przygoda',
  image_url: '/images/letni/hero.jpg',
  editionBadge: '11. edycja · zapisy otwarte',
  heroLine1: 'Letni obóz, na który',
  heroLine2: 'czeka się cały rok.',
  heroSubtitle:
    '25 lipca – 2 sierpnia 2026 · Janów Lubelski, Ośrodek ZOOM Przygoda. Akrobatyka, tricking, kajaki, longboardy, paintball i przyjaźnie na całe życie.',
  description:
    '<p>Air Camp to obóz sportowo-rekreacyjny prowadzony przez trenerów Air Squad. To nie jest siedzenie w stołówce — to sport i ruch, nowi przyjaciele, przygody i pewność siebie, którą dziecko przywozi do domu razem z pamiątkami.</p><p>To już jedenasta edycja obozu — organizujemy je nieprzerwanie od 2016 roku. Tegoroczna edycja odbędzie się w ośrodku ZOOM Przygoda w Janowie Lubelskim, tuż przy zbiorniku wodnym, a program dnia dopasowujemy do wieku i poziomu sprawności uczestników. Opiekę sprawuje 12-osobowy zespół trenerów — od akrobatyki i trickingu, przez judo i street workout, po showdance i fizjoterapię — pod kierownictwem Gabriela Myśliwca i Łukasza Pacochy. W cenie: zakwaterowanie w 8-osobowych domkach z pełnym węzłem sanitarnym, pełne wyżywienie, transport na miejsce i z powrotem, ubezpieczenie NNW, pamiątkowa koszulka oraz zdjęcia i filmiki z obozu.</p>',
  stats: [
    { value: '9', label: 'dni obozu' },
    { value: '20', label: 'kadra trenerów' },
    { value: '20+', label: 'aktywności' },
    { value: '11.', label: 'edycja Air Camp' },
  ],
  activityCards: [
    { label: 'Akrobatyka i Tricking', desc: 'Salta, przerzuty i efektowne tricki — od podstaw do zaawansowania.', accent: 'var(--primary)', img: '/images/bg-akrobatyka.jpg' },
    { label: 'Longboardy', desc: 'Pierwsza jazda albo dopracowanie triku — deski do wypożyczenia.', accent: 'var(--cyan)', img: '/images/bg-longboard.jpg' },
    { label: 'SUP / Kajaki', desc: 'Wolność na wodzie pod okiem instruktorów WOPR.', accent: 'var(--accent)', img: '/images/old-site/aircamp-wodny.jpg' },
    { label: 'Taniec i Showdance', desc: 'Nowoczesne choreografie w stylu commercial.', accent: 'var(--pink)', img: '/images/bg-showdance.jpg' },
    { label: 'Paintball', desc: 'Adrenalina gwarantowana — sprzęt i amunicja zapewnione.', accent: 'var(--amber)', img: '/images/letni/galeria-paintball.jpg' },
    { label: 'Terenówki', desc: 'Off-road po bagiennym terenie — ekscytująco i bezpiecznie.', accent: 'var(--violet-soft)', img: '/images/bg-aircamp.jpg' },
    { label: 'Gry terenowe', desc: 'Marsz na orientację, biegi przeszkodowe, integracja.', accent: 'var(--emerald)', img: '/images/old-site/mlodziez-oboz.jpg' },
    { label: 'Plaża i ogniska', desc: 'Skimboard za dnia, karaoke i ognisko wieczorem.', accent: 'var(--cyan)', img: '/images/letni/hero.jpg' },
  ],
  videos: [
    { url: 'https://airsquad.pl/wp-content/uploads/2025/03/aircamp25zapowiedzig.mp4' },
    { url: 'https://airsquad.pl/wp-content/uploads/2025/03/rolka-wpadanie-do-wody-3.mp4' },
    { url: 'https://airsquad.pl/wp-content/uploads/2024/02/VID_375100831_130120_230.mp4' },
    { url: 'https://airsquad.pl/wp-content/uploads/2025/12/reels-tor-przeszkod-dzien-3.mp4' },
  ],
  youtubeId: '-P1J3YntBpY',
  program: [],
  pricing: [
    {
      badge: 'Dla klubowiczów',
      dates: '25.07 – 02.08 2026',
      price: '2 600',
      accent: 'cyan',
      features: [
        'Cena obowiązuje członków klubu',
        'Codzienne zajęcia z akrobatyki',
        'Warsztaty i zajęcia podzielone na stopień zaawansowania',
      ],
    },
    {
      badge: 'Acro Open',
      dates: '25.07 – 02.08 2026',
      price: '2 800',
      accent: 'primary',
      features: [
        'Cena dla osób spoza klubu Air Squad',
        'Wszystkie atrakcje i opieka w cenie obozu',
        'Zajęcia z akrobatyki zależnie od poziomu uczestnika',
      ],
    },
  ],
  includes: null,
  form_url: null,
  aipaxFormId: '71f55506-fe65-46b1-a777-2ce1660b0c32',
  faq: [
    { question: 'Od jakiego wieku dziecko może jechać na Air Camp?', answer: 'Obóz jest dla dzieci i młodzieży od 8 do 16 lat. Grupy dobierane są wg wieku i poziomu sprawności.' },
    { question: 'Co jest wliczone w cenę?', answer: 'Nocleg, pełne wyżywienie, opieka trenerów 24h, sprzęt do wszystkich aktywności, transport na atrakcje oraz koszulka i pamiątki obozowe.' },
    { question: 'Czy trzeba umieć pływać albo jeździć na longboardzie?', answer: 'Nie — wszystkie zajęcia zaczynają się od podstaw. Instruktorzy WOPR nadzorują aktywności wodne niezależnie od poziomu umiejętności.' },
    { question: 'Jak wygląda transport na obóz?', answer: 'Organizujemy zbiórkę i transport autokarowy z Rzeszowa — szczegóły otrzymasz w potwierdzeniu zapisu.' },
  ],
  gallery: [
    { url: '/images/letni/galeria-akro.jpg', caption: '// akrobatyka na plaży' },
    { url: '/images/letni/galeria-kajaki.jpg', caption: '// kajaki i SUP na jeziorze' },
    { url: '/images/letni/galeria-paintball.jpg', caption: '// paintball w lesie' },
    { url: '/images/bg-aircamp.jpg', caption: '// obóz Air Camp' },
    { url: '/images/old-site/dzieci-airtrack.jpg' },
    { url: '/images/old-site/tricking.jpg' },
    { url: '/images/old-site/tumbling.jpg' },
    { url: '/images/old-site/dorosli-ekipa.jpg' },
    { url: '/images/old-site/mlodziez-oboz.jpg' },
    { url: '/images/old-site/hala-airspace.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/f87b4285-28ae-45d3-8e4d-24c9c0457539.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/f83f19a4-9701-4425-bbef-b593dcc0b91c.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/f78ca1e4-2d35-42a5-957b-cf11b0d46d71.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/f11df621-5cb3-48a4-bc17-a9882e03a5fd.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/e9e68528-1541-43a3-af8b-f39c8ff0d62f.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/e1459793-8899-481a-ae59-e2a6db94169a.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/df806088-7151-4648-86bc-cb8872358a9b.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/d776cd51-0bae-4ce5-a238-ef7d132bf83c.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/d71f5f44-9fe4-4fb3-bd50-914131939ad9.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/d17128e1-ec4b-4f51-8ea6-2fa38b79b3e7.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/cfd79c5a-0b72-4a8e-9403-113b1a831c38.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/cfbede5c-2b05-403d-a584-8f6bd457370d.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/cda053ab-fdf2-46fd-8939-17e62f446fd4.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/cbe76872-0b95-474e-a28b-a0fd7da99ff5.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/cb5a3e55-eae3-4947-834d-3fcff62e69e5.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/c77f1a2c-4373-4c65-88bb-464a6c6a7f2c.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/c48aded3-4c60-46c8-961c-a838c96706e0.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/c061055a-043b-44df-bbef-40cffb4e721e.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/b93ba08d-4b6a-4915-ad4c-e58ddee52d42.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/b82eba2e-ae75-4c3b-b92f-9db7ec524bf4.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/b258aa84-0fa7-4271-a90d-f6b8895a6a18.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/b01449f0-6a3f-4000-9ac0-8498c68e73f5.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/a67735ea-f943-4677-a8ff-2731dafc856d.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/a2db1363-acb3-472e-ac70-bf4bc8b3ce50.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/a25fd8f4-e44d-4783-bd2c-6ec2625f1d5a.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/a215198a-6c1c-4a1f-9c9d-422eb151371c.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/8fb081e7-c89f-4c11-92d5-500e2f2dfc8c.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/8ed2ee61-d886-439a-a1bd-f09aa74c416b.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/83e9c04d-b6db-44d3-bdc7-6d7c9f95331d.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/6fa37cfd-bed8-49fc-bb18-06df12891d32.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/67fad3fa-82d9-49a3-ab17-b258c2849142.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/5f18f1e4-4ae9-47bc-85f8-9713d875639a.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/5cddc16d-fcc2-4785-963a-8529ceb3f6ef.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/58c23da1-fd26-4458-913e-caa2b1e5f2e8.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/508bf8e2-3be3-4dcc-85b3-fe5f48dd22e7.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/501eca49-fff2-4ddb-a522-98a8e9ea78ef.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/4f438eb0-7dcf-4b6c-812f-12ef7aedd1c6.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/482249de-4c8c-4d6c-8a93-f7bcfc1e4ed1.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/43a2d3a5-33be-4cd6-871f-8796f337ab2d.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/3bea93cd-ae9b-492e-b3bf-d734debacdbd.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/29d6c59f-3cbe-4faa-bfa2-b4461bb6fdc6.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/26e3923f-d25f-4d28-874a-7885af9a026c.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/249b5429-1975-4f70-97c2-c83581f7d21c.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/1f219eab-5d2e-42ff-bffc-d1024906ce9a.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/1dfe504e-d303-4d40-bc30-4c6fc65b122e.jpg' },
    { url: 'https://airsquad.pl/wp-content/uploads/2026/01/1d4ad34c-c654-4e6e-9379-29459f43b822.jpg' },
  ],
  is_active: true,
  is_published: true,
  created_at: '',
  updated_at: '',
}

// Fallback treści /airmeeting/ i /gravityjam/ — treść wzięta z już zatwierdzonych
// opisów na stronie głównej (components/home/promo-section.tsx), żeby nowy
// dropdown „Obozy i wydarzenia" w menu nie prowadził na puste strony 404.
// Po podłączeniu i zaseedowaniu bazy wiersz z DB ma priorytet.
export const AIRMEETING_EVENT: Event = {
  id: 'fallback-airmeeting',
  slug: 'airmeeting',
  title: 'Air Meeting 2026',
  meta_title: 'Air Meeting 2026 — zlot akrobatyczny | Air Squad',
  meta_description:
    'Air Meeting 2026 — spotkanie, zawody i wspólne emocje. Niezapomniane wydarzenie dla członków klubu Air Squad.',
  event_type: 'airmeeting',
  event_date: null,
  event_time: null,
  location: 'Podkarpacie',
  tagline: 'spotkanie, zawody, wspólne emocje.',
  image_url: null,
  description:
    '<p>Spotkanie, zawody i wspólne emocje. Niezapomniane, przepełnione pozytywną energią wydarzenie dla członków klubu Air Squad. Szczegóły najbliższej edycji wkrótce.</p>',
  program: [],
  pricing: [],
  includes: null,
  form_url: null,
  stats: [],
  attractions: [],
  gallery: [],
  is_active: true,
  is_published: true,
  created_at: '',
  updated_at: '',
}

export const GRAVITYJAM_EVENT: Event = {
  id: 'fallback-gravityjam',
  slug: 'gravityjam',
  title: 'Gravity Jam — święto kultury ulicznej',
  meta_title: 'Gravity Jam — jam akrobatyczny i święto kultury ulicznej | Air Squad',
  meta_description:
    'Gravity Jam — warsztaty rolkowe, akrobatyczne, strefa longboardowa i gier drewnianych. Air Squad razem z MB Park i Street Life Rzeszów.',
  event_type: 'gravityjam',
  event_date: null,
  event_time: null,
  location: 'Rzeszów',
  tagline: 'święto kultury ulicznej.',
  image_url: null,
  description:
    '<p>Warsztaty rolkowe, akrobatyczne, strefa longboardowa i gier drewnianych. Gravity Jam to wspólna inicjatywa Air Squad, MB Park i Street Life Rzeszów.</p>',
  program: [],
  pricing: [],
  includes: null,
  form_url: null,
  stats: [],
  attractions: [],
  gallery: [],
  is_active: true,
  is_published: true,
  created_at: '',
  updated_at: '',
}

export const FALLBACK_EVENTS: Record<string, Event> = {
  letni: LETNI_EVENT,
  airmeeting: AIRMEETING_EVENT,
  gravityjam: GRAVITYJAM_EVENT,
}
